services:
  server:
    build:
      context: ./server        # Point to the server directory where the Dockerfile is located
      target: build            # Target the build stage in your Dockerfile
    volumes:
      - ./server:/app          # Mount the local server directory
      - /app/node_modules      # Exclude node_modules from being overwritten
    ports:
      - "${DEV_PORT}:3000"     # Use DEV_PORT from .env
    command: npm run dev       # Development mode
    env_file:
      - .env                   # Load environment variables from the .env file
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "${DEV_POSTGRES_PORT}:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${DEV_REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgresql:
  redis_data:
